# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact to download'
        required: false
        type: string
        default: dist
    outputs:
      myresult:
        description: 'An example output value'
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secret:
    #     required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.set-output.outputs.result }}
    steps:
      - name: Output message
        run: echo "This is a reusable workflow!"
      - name: Get test report
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.artifact-name }}
      - name: List contents
        run: ls -l
      - name: Set Output
        id: set-output
        run: echo "result=success" >> $GITHUB_OUTPUT