# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable Workflow
on: workflow_dispatch
jobs:
  reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - id: example-step
        run: echo "myvar=111" >> "$GITHUB_OUTPUT"
      - name: print
        run: echo ${{ steps.example-step.outputs.myvar }}